### ISSUE TITLE
As a team leader I want to see details of pending absence requests so that I can action them

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#11]
AC01: Can I see details of the absence request? For example Name, Request dates
AC02: Can I click on the the absence request to action it?
AC03: Can I see a note showing whether the request is approved or declined?

**Comment by stevenhaynes** [comment]
Incorporated in the dashboard. May have already been implemented.

**Comment by Michael-B-Lee** [comment]
The absence requests can now be clicked on, but are only partially functioning. The approved button shows a note as seen in the design, whilst the decline button opens a pop up asking for confirmation. The pop up still needs to be styled according to the design in addition to adding a note stating that the request has been declined.

**Comment by Michael-B-Lee** [comment]
Absence requests now fully work with static data. Requests are now updated based on which button is pressed. The confirmation pop up has been styled and is working as intended. A new popup has been added that activates when the request is clicked on. This popup shows additional details about the request and has been fully styled to look like the designs.

**Comment by JohnThirlaway1** [comment]
cleared merge conflicts with the master branch and intergrated within the story together with Mike. We have made a lot of progress however there maybe a few things which need cleaned up.
