### ISSUE TITLE
Password: Update password functionality

### ISSUE THREAD

**Issue by KatherineGoldklang** [innovationprogrammeuki/Absences#116]
- User to be able to update their password from the default provided

**Comment by JohnThirlaway1** [comment]
Picking this story up now, currently got the modal working and connecting the web services to it

**Comment by JohnThirlaway1** [comment]
web service have been connected to this functionality, and will allow the user to update their password. However I am still working on further validation to stop the user from being able to add an empty string and giving the user feedback if the password fields are not filled out correctly.

**Comment by JohnThirlaway1** [comment]
Functionality has been completed and is currently within code review
