### ISSUE TITLE
As a team member I want to see how much holiday I have to used so that I can monitor how many I have left

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#13]
AC01: Can I see the amount of holidays that I've used?
AC02: Can I see the amount of holidays I have remaining?

**Comment by AlexJYoungman** [comment]
Currently there is an indicator on the calendar work that shows days remaining, as per the designs.
The value is currently hardcoded.

**Comment by AlexJYoungman** [comment]
Similar to the days remaining there are several sections that show the days used for different types of absence, as per the designs.
