### ISSUE TITLE
As a team member I want to see my calendar at a yearly view to that I can quickly see my absences

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#14]
AC01: Can I see a yearly calendar view?

**Comment by AlexJYoungman** [comment]
Yearly calendar view is done in terms of presentation. It displays each day of each month along with the month name. It also accounts for leap years.
It reads from a JSON object that stores a series of absences, each with a start and end date.
Each absence has it's own colour and a tool-tip with matching styling.
