### ISSUE TITLE
As a team member I want to add an absence requests to my calender so that it can be requested

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#15]
AC01: Does the calendar allow me to select a day?
AC02: Does the calendar allow me to drag-select multiple days?
AC03: Can I submit the request?
AC04: Does the calendar show my absence request after it's been submitted?

**Comment by AlexJYoungman** [comment]
Currently the create absence popup is created in line with the designs. Purely for display though, no functionality added yet.

**Comment by AlexJYoungman** [comment]
A date picker has been integrated into the popup and will change the appropriate text box.

**Comment by AlexJYoungman** [comment]
Popup is now integrated with the create absence button, and the click and drag functionality. Carrying in the selected dates. When accepted the new pending request is reflected on MyCalendar.
