### ISSUE TITLE
As a team member I want to click on absences so that I can see more details

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#16]
AC01: Can I see more details of the absence when it's clicked?

**Comment by stevenhaynes** [comment]
This story refers to the pop up box in the designs

**Comment by JohnThirlaway1** [comment]
Pulled from the backlog to work on this story, due to Alex picking up  storypoint 17 due to complexity.

**Comment by JohnThirlaway1** [comment]
Pulled down Alex's merge from github after he merged into master once everything was approved and will be working on this tomorrow .

**Comment by JohnThirlaway1** [comment]
I have not been able to progress this story as of yet as I have been working on storypoint 9 today to get it finished as quickly as possible

**Comment by JohnThirlaway1** [comment]
Spoke with Alex in regards to building this functionality from his exsisting code, he has pointed me in the correct direction and I will be working on this from Monday

**Comment by JohnThirlaway1** [comment]
Worked on this story today have everything functional and style wise completed, just the close button and  background opacity to change.  However this story has been progressed alot today and making good progress.

**Comment by JohnThirlaway1** [comment]
Completed styling, and added close functionality. This story is ready for code review and has been pushed it to github

**Comment by JohnThirlaway1** [comment]
story was code reviewed by ryan,  he suggested a few small changes in the form of indentation. I have made these and pushed my code back to the feature branch ready for a further code review.

**Comment by JohnThirlaway1** [comment]
Ryan approved code review. Joe pushed back with a request to remove a comment. I have completed and pushed the code back for review and has been accepted. Natalie to do a UI review and will update with her outcome.

**Comment by JohnThirlaway1** [comment]
this functionality as needs applied to the Team Calendar which is extra work, found this out while having a UI review with Natalie. I will add this functionality.

**Comment by JohnThirlaway1** [comment]
This story has been on the back burner today, it has been code reviewed and passed however the component also needs to be added to the team calendar section.

**Comment by JohnThirlaway1** [comment]
Alex has help progressing this story today and has prept ready for the web services to be connected. Awaiting code review
