### ISSUE TITLE
Dashboard: Half days are not refunded correctly on decline

### ISSUE THREAD

**Issue by AlexJYoungman** [innovationprogrammeuki/Absences#161]

**Comment by AlexJYoungman** [comment]
Currently working on a script to convert from the old integer value to a decimal value in the database.

**Comment by stevenhaynes** [comment]
What's the latest with this one. Can it be move back into In-Progress?

**Comment by AlexJYoungman** [comment]
Just waiting on the web service side from @AccentSandeep

**Comment by AccentSandeep** [comment]
As we were facing issues last friday due to .jar files not included in the versioning system. I'll make the changes from my end and deploy the web service and then will look into changing the project build system to either Maven or Gradle if possible

**Comment by AccentSandeep** [comment]
Done

**Comment by danieljtate** [comment]
1. Go to create absence
2. Create a half day request
3. Check balance
4. Decline request
5. balance increases by 0.5

[passed]
