### ISSUE TITLE
Approving absences

### ISSUE THREAD

**Issue by KatherineGoldklang** [innovationprogrammeuki/Absences#168]
Noticed on Sarah's account. 

Sarah could view a selection of absence requests. However, she couldn't see all of the absence requests which had been submitted to her. 

On approving/declining absences, she found that one remaining absence could not be declined. On refreshing the page, the absence could still not be declined (WFH request - see bug 158), and the rest of the remaining absence requests which had been submitted still did not show. 

I logged into sarah's account on my machine. I could now see all the other absence requests (but not the one which could not be declined). I could approve/decline these absences bar one. This one was different to the original absence request which could not be approved or declined - it was an 'other' request.

**Comment by JohnThirlaway1** [comment]
I will take a look into this bug and try and replicate the error to get a better idea if it still persists and if so what could be the issue.

**Comment by JohnThirlaway1** [comment]
After recreating the steps which Katharine on the latest update on the development branch it seems this bug has been resolved, it will be in place once it has been pushed to the server.

**Comment by AlexJYoungman** [comment]
Test 1

1. Launched and logged into Absences as a standard user
2. Navigated to my calendar
3. Put in a request for WFH
4. Logged out and logged into Absences as the chosen approver
5. Declined the WFH request on the dashboard
6. Request was successfully declined.
7. Logged back in as standard user and verified WFH request was gone

Passed
