### ISSUE TITLE
As a team member I want to see the company calender so that I see when my peers are absent

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#17]
AC01: Can I see who is  absent as per wireframes?
AC02: Am I able to see the type of absence?
AC03: Can I search the list by names to display a certain user?
AC04: Does my Page align with the UI design?

**Comment by stevenhaynes** [comment]
I'd suggest we create a D3 component for this like we have the yearly calendar. It would be good to get someone else in the team to up skill in this with help from Alex. Or even have Alex and someone else pair programming full time.

**Comment by JohnThirlaway1** [comment]
I'll pick this story up and speak to Alex later today to get a better understanding of how to get the story started.

**Comment by JohnThirlaway1** [comment]
Took a look at D3 over the weekend and have some helpful resources for this story, I will speak to Alex  in how best to intergrate the JS into React JS

**Comment by JohnThirlaway1** [comment]
D3 doesn't support gantt chart functionality, there is a user created function however after sitting down with alex we have been unable to get it to function. I have looked at Google Charts, however this doesn't look to be a viable option as it doesn't allow multiple tasks on one  swimlane. Alex has pointed me towards a Javascript frame work called  vis.js which I am currently taking a look at

**Comment by JohnThirlaway1** [comment]
After spending today working with the Google Charts functionality with this story I feel the framework doesn't have enough freedom to create the functionality and look and feel of the UI. Raised this with Steven, he advised if possible could Alex pick this up as it may need a full component built and I feel my skill level would cause latency on delivering on the sprint. Alex has kindly said he will pick this story up and I plan on either picking up a story from the backlog or helping the rest of the team with there stories.

**Comment by AlexJYoungman** [comment]
An initial timeline chart has been implemented showing basic data and colour coding each item. Planning on working on styling to fit with the designs and then working on possibly a search function.

**Comment by AlexJYoungman** [comment]
Timeline is functional and in line with UI designs. Search is also functioning. Awaiting some design feedback before push.
