### ISSUE TITLE
As a user, I want to be able to delete an event in My Calendar and Team Calendar so that if it's no longer needed, it's not recorded unnecessarily

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#172]

**Comment by stevenhaynes** [comment]
Can we consult on weather the absence should be deleted from the database or it's status just changing?

**Comment by AlexJYoungman** [comment]
Testing

1. Opened Absences and logged in
2. Navigated to my calendar 
3. Clicked an absence and clicked delete

Failed. Delete does not work.

**Comment by danieljtate** [comment]
Testing

[My Calendar]
1. opened my calendar
2. selected an absence
3. clicked delete

deletes the absence

Passed

[Team Calendar]
1. opened team calendar
2. selected absence
3. clicked delete

error

Failed

**Comment by TheGarrett** [comment]
Testing

[My Calendar]

opened my calendar
selected an absence
clicked delete
deletes the absence

Passed

[Team Calendar]

opened team calendar
selected absence
clicked delete
deletes the absence

Passed
