### ISSUE TITLE
As a system, bank holiday events will be automatically populated from a datasource

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#173]

**Comment by stevenhaynes** [comment]
Possibility? https://www.gov.uk/bank-holidays.json

**Comment by AlexJYoungman** [comment]
Didn't realise you had put this link here Steven, but I managed to find it through my research. Functionality is added, you cant begin or end holidays on bank holidays and they arent included when counting the days used for a holiday. They display correctly on the calendar, just awaiting code review.

**Comment by danieljtate** [comment]
1. Go into My Calendar
2. Cannot select bank holidays from the calendar
3. Click Create Absence
4. Cannot use Create Absence to select bank holidays

[Passed]
