### ISSUE TITLE
As a system, all endpoints will be secure so that the application has to authenticate before handling data

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#174]

**Comment by AccentSandeep** [comment]
Here is an update on this story

To add security to the  Absence web services - oAuth token based authentication mechanism has been implemented. Once this implementation is deployed, all actions like Read, Write, Update & Delete needs to be authorised first to perform the desired action.

This is where i am in terms of implementation.

1. Implementation of token based authentication is completed. Now the client/browser  will have to request a token by visiting a "/oauth/token" endpoint and providing valid authentication details 
2. Once validated, the server will return a token with a validity of an hour. After the token is expired new token needs to be requested.
3. This implementation alone is enough for securing the Web service but just to streamline the process and to add more flexibility & security,  I am currently working on the token refreshing mechanism making use of refresh token.

Here is a sample of a token response valid for user “steven.haynes@accenture.com” received back from /oauth/token endpoint.

{
  "expiresIn": 3600,
  "accessToken": "eyJhbGciOiJIUzUxMiIsInppcCI6IkRFRiJ9.eNqqViouTVKyUiouSS1LzdPLSKzMSy12SExOTs0rKS1K1UvOz1XSUcpMLFGyMjSxMDAwt7A0NdZRSq0ogApYGJmaGtcCAAAA__8.BQkkJFdc-5jGtH80zNbaOAz_POUT0bU0OW7TvkcUNKryOXQsS3rNXnKS6lJ7F5bZ7uZ7ilBpiFp0zagDE8G-VQ",
  "tokenType": "Bearer",
  "refreshToken": "qu21ich4j8v69l4a2trisam5nt"
}

**Comment by AccentSandeep** [comment]
The development on this issue has been completed and have been deployed to the dev environment yesterday.
