### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#176]

**Comment by stevenhaynes** [comment]
1) Standardise code throughout all files.
2) Remove redundant code stripping it back as much as possible.
3) Check naming conventions and function naming.
4) Use a global CSS file for common styles.
5) Check with Adam Kelly on how to manage environment variables? Should they be in a config file?
6) Ensure code is commented.

If you think of any more please add them.

**Comment by AlexJYoungman** [comment]
Some files (including Dashboard.js) need tabulating correctly.
