### ISSUE TITLE
As a user, I want to be able to see overlapping absences when I create and view an absence so that I know who's absent at the same time as me

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#179]

**Comment by stevenhaynes** [comment]
Suggest we only show overlapping absences in the team your assigned to.

**Comment by MoustafaBounasser** [comment]
Why is this story still in the backlog?

**Comment by Michael-B-Lee** [comment]
Overlapping absences feature now works when viewing absence requests on the dashboard page. Further work is required to integrate it with the create absence modal as it needs to constantly update based on the dates that have been selected.

**Comment by stevenhaynes** [comment]
Test 1

1. Launched and logged into Absences
2. Clicked the My Calendar tab
3. Clicked Create Absence

Fail. All the months of the years are displaying under overlapping absences and a long string of numbers next to each one.

Test 2

1. Launched and logged into Absences
2. Clicked the Test Calendar tab
3. Clicked an absences
4. Click overlapping absences
5. Verified that overlapping absences display

Passed

@natalietolley @robtulip can you look at the UI for overlapping absences and feedback any comments. Looks clunky on the dev environment.

**Comment by Michael-B-Lee** [comment]
Changes have now been made to this feature that fix the UI bugs and string of numbers error. The code has been pushed, passed review and is currently waiting to be tested.

**Comment by AlexJYoungman** [comment]
Testing

1. Opened and logged into absence
2. Navigated to my calendar
3. Clicked create absence
4. Changed date to one another employee is absent on

Failed. Overlapping absences does not work anywhere.

**Comment by Michael-B-Lee** [comment]
links to #234

**Comment by Michael-B-Lee** [comment]
links to #219

**Comment by AlexJYoungman** [comment]
When testing I can't see any overlapping absences. Can you check this on the dev server @Michael-B-Lee

**Comment by JohnThirlaway1** [comment]
Testing

Opened and logged into absence
Navigated to my calendar
Clicked create absence
Changed date to one another employee is absent on
displayed that there was an overlapping absent and displayed their details on the drop down

Status: Passed
