### ISSUE TITLE
As a user, I want to land on the correct view when I log in

### ISSUE THREAD

**Issue by KatherineGoldklang** [innovationprogrammeuki/Absences#18]
AC01 If I log in as a team lead, do I  land on the dashboard summary page?

AC02 If I log in as a team member, do I  land on my absences page?

**Comment by JohnThirlaway1** [comment]
Due to the lack of web services at the moment, I not able to give user permissions. at the moment from what I have built in from storypoint 25 all user are pushed to "my Calendar" screen once pressing the login button.
