### ISSUE TITLE
As a user, I only want to be able to see sub-tractable balances on specific absence types so that I don't get confused with what I have remaining

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#182]

**Comment by stevenhaynes** [comment]
When creating a new absence and selecting for example Training, your absence balance shows a deduction.

For Holidays we should show a 'Holiday Balance' as is now. If you chance the Absence type to Charity Day you should see a 'Chart Day Balance'. If the Type is changed to Training there should be no balance and it's not sub-tractable. The component that shows the balance should be hidden.

May require some UI support @natalietolley @robtulip

**Comment by AlexJYoungman** [comment]
This functionality is slightly different currently. We currently have it so that if holiday is selected then a subtraction is shown. However if any other options are selected (training etc) then the subtracting value is shown as 0. 
Its up to you if you would rather we hide the subtracting component all together.
But yes the functionality has already been changed slightly.

**Comment by AlexJYoungman** [comment]
@stevenhaynes Will need clarification on whether this requires further development or the functionality we added is sufficient.

**Comment by Michael-B-Lee** [comment]
Holiday balance is now hidden when any option is selected, excluding holidays. Balance is also hidden for charity days as this data is not currently tracked anywhere in the system.

**Comment by AlexJYoungman** [comment]
Testing

1. Opened absences and logged in
2. Navigated to my calendar page
3. Clicked create absence
4. Verified that the holiday balance component is showing for holiday
5. Verified component disappears when selecting a non holiday type
6. Verified that component re appears when selecting holiday again

Passed
