### ISSUE TITLE
Creating holidays on a weekend day

### ISSUE THREAD

**Issue by MoustafaBounasser** [innovationprogrammeuki/Absences#183]
a bug in the absence creation functionality:
it allows the creation of an absence on a weekend day (shouldn't).
it messes up the day's cell by printing the absence type into it

**Comment by MoustafaBounasser** [comment]
<img width="1379" alt="screen shot 2016-11-28 at 11 09 09" src="https://cloud.githubusercontent.com/assets/20184217/20666446/25e5e1c8-b55c-11e6-9d49-c2db184a7230.png">

**Comment by AlexJYoungman** [comment]
This issue has already been fixed. It just isn't on the server.

**Comment by JohnThirlaway1** [comment]
added further styling to this issue rather than just an alert, now is within a modal.

**Comment by JohnThirlaway1** [comment]
Screen Shot 2016-11-28 at 14.57.39.png

**Comment by TheGarrett** [comment]
Test 1
1. Launched the application.
2. Logged into Absences.
3. Clicked 'Create absence'.
4. Selected days on a weekend And submitted.
5. Message popped up saying that I couldnt sumbit holiday on weekend.

PASSED
