### ISSUE TITLE
Absence creation

### ISSUE THREAD

**Issue by MoustafaBounasser** [innovationprogrammeuki/Absences#184]
as a user when creating a new absence i want to:
AC01- when selecting a from date my to date should change to the same date as the selected date.
AC02- my to date should never be prior to my from date

**Comment by AlexJYoungman** [comment]
1. Launched and logged into Absences
2. Navigated to my calendar page
3. Clicked create new absence
4. Changed start date
5. Verified that the end date changed to match the start date.
6. Changed the end date to be prior to the start date
7. Clicked create
7. Verified i was unable to complete absence creation.

Passed
