### ISSUE TITLE
As a system, I want to block users from adding holidays in the past

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#185]

**Comment by stevenhaynes** [comment]
@kieranmcnay might be a good one for you to pick up

**Comment by kieranmcnay** [comment]
Implemented function that prevents users from entering an absence before the current date, when a user tries to do so an error pop up is displayed and the request is cancelled.

i have created an IF statement to make it so only holiday absences are blocked when adding in the past but i am yet to test its functionality as of errors when using the local host

**Comment by stevenhaynes** [comment]
What's the latests with this?

**Comment by kieranmcnay** [comment]
Just need to test it  to see if its functional and then it will be completed and ready to merge.

**Comment by kieranmcnay** [comment]
Code has been tested and is functional, is awaiting code review.

**Comment by AlexJYoungman** [comment]
Testing

1. Opened absences and logged in
2. Navigated to my calendar page
3. Attemped to make holiday before todays date

Passed. I am unable to directly make a holiday before today.

4. Made a sickness before today.
5. Changed the sickness to be a holiday

Failed. This allowed me to create a holiday in the past.
The edit feature wasn't implemented when Kieran implemented this functionality so i would not count it as a defect, however Kieran should now go back and add this feature to the Edit Absence page.

**Comment by AlexJYoungman** [comment]
Testing

1. Opened absences and logged in
2. Navigated to my calendar page
3. Selected a request in the past that wasn't holiday
4. Attempted to change to holiday

Passed. I was prevented from changing a past absence to a holiday.
