### ISSUE TITLE
As an admin, I want to be able to sort by alphabetical order in users on User, Team, Project and Role so that I can easily find who i'm looking for

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#186]

**Comment by JohnThirlaway1** [comment]
Test 1: 

-As an approver I logged into the tool and navigated to the users page.
- As a user I filtered alphabetically on users, teams, projects and role successfully.
- As a user I changed my team on the top left to unassigned and then pressed filter name which then pushed all users into the table under the wrong team.

Status: Failed

**Comment by AlexJYoungman** [comment]
Testing

1. Opened absences and logged in
2. Navigated to users page
3. Changed to a team with a few users
4. Clicked the sort arrow
5. Verified the same users were showing after sort

Passed
