### ISSUE TITLE
As a system I want to make use of a token system for authenticating web service calls

### ISSUE THREAD

**Issue by AlexJYoungman** [innovationprogrammeuki/Absences#188]

**Comment by AlexJYoungman** [comment]
The issue has been potentially discovered and Sandeep is working on a solution to it. A fix should be arriving soon.

**Comment by danieljtate** [comment]
Testing in the morning alongside #196

**Comment by danieljtate** [comment]
1. logged into system
2. waited for token to expire
3. once token expired tried to make a call to the service
4. Error showed and logged out 

[passed]
