### ISSUE TITLE
As a user, I want my absences to be stored in a database

### ISSUE THREAD

**Issue by KatherineGoldklang** [innovationprogrammeuki/Absences#19]
AC01: Data is stored within a database
AC02: From the database, data can be pulled to the front end

**Comment by stevenhaynes** [comment]
1) From the designs understand what data is to be stored.
2) Look up Primary and Foreign keys on the internet.
3) Map out a set of tables on the glassboards (John T to lead, he has some database knowledge).

Once we have the above creating the MySQL database is quick. The most time consuming part is deciding what goes it what table.

**Comment by danieljtate** [comment]
Assigned the story and will be looking at what data could be stored, possible PK and FK within the tables then discuss with the rest of the team which parts should be included in where

**Comment by JohnThirlaway1** [comment]
working on the Dashboard integration currently

**Comment by JohnThirlaway1** [comment]
Dashboard has been hooked up to some of the web services however the absence request and pie chart haven't been

**Comment by JohnThirlaway1** [comment]
absence approval section has been mostly hooked up and integrated with the webservices. However there still appears to have a few persisting bugs.

**Comment by JohnThirlaway1** [comment]
dashboard approvals section has been completed and pushed to code review, it has had it's bugs cleared and removed the notify section as was uneeeded and added complexity to the dev time, passed this by Katharine and Steven before removing who agreed it was okay.

**Comment by JohnThirlaway1** [comment]
Dashboard Approvals merged into Master
