### ISSUE TITLE
As an admin I would like to be able to assign one or several people to different Teams or Projects from the users page

### ISSUE THREAD

**Issue by danieljtate** [innovationprogrammeuki/Absences#195]

**Comment by AlexJYoungman** [comment]
Test 1
1. Launched and logged into Absences
2. Navigated to users page
3. Selected three users
4. Clicked assign team
5. Chose team and approved
6. After page refresh, verified that the chosen users had the new team

Test 2
1. Launched and logged into Absences
2. Navigated to users page
3. Selected three users
4. Clicked assign project
5. Chose team and approved
6. After page refresh, verified that the chosen users had the new project

Test 3
1. Launched and logged into Absences
2. Navigated to users page
3. Selected three users
4. Unselected all users
5. Verified that assign buttons are now disabled

Passed
