### ISSUE TITLE
When approving/declining a request the page should update

### ISSUE THREAD

**Issue by danieljtate** [innovationprogrammeuki/Absences#200]

**Comment by JohnThirlaway1** [comment]
I will pick this up for testing, conclusion to be below.

**Comment by JohnThirlaway1** [comment]
Test 1: 

- Once logging onto the application as an approver, I am able to see the dashboard page
- Once pressing accept on a holiday request, the button then reflects the user input. and then refreshes the screen updating the list.
- Once pressing decline on a holiday request, the button then reflects the user input. and then refreshes the page updating the list.

Status : Passed
