### ISSUE TITLE
Dashboard - select day to display absence

### ISSUE THREAD

**Issue by KatherineGoldklang** [innovationprogrammeuki/Absences#205]
connects to

**Comment by JohnThirlaway1** [comment]
this is connected to 204, the user now has the availability to change and view the breakdown of absences. It has been code reviewed and now merged into development

**Comment by TheGarrett** [comment]
Test failed as when I change the date, the pie seems to break.

**Comment by JohnThirlaway1** [comment]
PIe chart now displays, however there is a  bug, once a user selects a day which has no absences and are displayed the message. From this, they click on another day which does have absences the list appears however the pie doesn't until the user clicks on another consecutive day with  absence data. Currently trying to find what is causing the error.

**Comment by JohnThirlaway1** [comment]
bug has been found and fixed now, was the result of function not being called in the correct order

**Comment by danieljtate** [comment]
Testing

1. Login to tool
2. Date picker shows current date as default
3. Can use date picker to select a new day
4. Selecting another day updates the list of absences and Pie Chart

Passed
