### ISSUE TITLE
As a system, when a component is loading, an appropriate element is displayed to inform the user

### ISSUE THREAD

**Issue by AlexJYoungman** [innovationprogrammeuki/Absences#207]

**Comment by JohnThirlaway1** [comment]
test 1:

- logged into the application as an approver
- Upon landing the Dashboard screen the components displayed a loading element.
- Upon landing the Calendar screen the components displayed a loading element.
- Upon landing the Team Calendar screen the components displayed a loading element.
- Upon landing the Users screen the components displayed a loading element.
- Upon landing the Settings screen the components displayed a loading element.

Status: Passed
