### ISSUE TITLE
As a system, when a component is loading, an appropriate element is displayed to inform the user

### ISSUE THREAD

**Issue by KatherineGoldklang** [innovationprogrammeuki/Absences#209]
AC01 - Can I see a loading icon when a component is loading?

AC02 - Does the icon disappear once component has loaded?

**Comment by joerushbrooke** [comment]
Test 1

1) Launched the application
2) Logged into Absences
3) Whilst waiting for components there is a spinning loading icon
4) When the component is loaded the spinning loading icon disappears

PASSED
