### ISSUE TITLE
As a user, I shouldn't be able to approve my own absences

### ISSUE THREAD

**Issue by KatherineGoldklang** [innovationprogrammeuki/Absences#217]

**Comment by JohnThirlaway1** [comment]
Managed to get the list to hide the current logged on user to search the admin list, and if it matches hide the select option to stop this issue from occurring.

**Comment by AlexJYoungman** [comment]
Testing

1. Opened absences and logged in as an approver
2. Navigated to my calendar page
3. Clicked create absence
4. Verified that the currently logged in user is not on the approvers list

Passed
