### ISSUE TITLE
As a system, I want to show 'Absences 1.1' on all referenced titles so that users know the application has been updated

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#224]

**Comment by kieranmcnay** [comment]
Changed all titles displaying Absences 1.0 to Absences 1.1 on the:
Navbar, Login screen and Page title

**Comment by AlexJYoungman** [comment]
Testing.

1. Logged into absence.
2. Visited each page
3. Verified that the title shows up as Absence 1.1 on each page
4. Verified that the title on the tab in browser shows as Absence 1.1

Passed
