### ISSUE TITLE
Remove rogue checkbox on Login Welcome Back screen

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#227]

**Comment by kieranmcnay** [comment]
Done, the checkbox was part of a function that was not used on the Absences website/ or referenced. Unnecessary code has been removed as a result

**Comment by AlexJYoungman** [comment]
Testing.

1. Opened up absence and made sure I'm logged out
2. Ensured that the checkbox was gone

Passed
