### ISSUE TITLE
As a team lead, I want to be able to see the settings page

### ISSUE THREAD

**Issue by KatherineGoldklang** [innovationprogrammeuki/Absences#23]
AC01: Can I see the settings page?
AC02: Can I change the settings?

**Comment by Michael-B-Lee** [comment]
Settings page is almost complete from a visual standpoint, having a few issues displaying the users assigned to a specific team/project

**Comment by Michael-B-Lee** [comment]
Settings page is visually complete, currently working on adding functionality for adding/removing teams, projects and users.

**Comment by Michael-B-Lee** [comment]
Code for settings page has been pushed in dashboard-approvals branch
