### ISSUE TITLE
As an admin I would like to be able to delete a user from the tool

### ISSUE THREAD

**Issue by danieljtate** [innovationprogrammeuki/Absences#230]

**Comment by JohnThirlaway1** [comment]
Testing Results:

- logged into the application
 - created a user called test.McTest using approver Login (steven.haynes) account.
- logged out of the application as Steven.haynes and proceeded to login with  test.McTest and added holiday request.
-logged out of test.McTest into Steven's account approved holidays for test and then deleted user.
- checked on  postman to see if any reference of the account was remaining which didn't appear. 

Status: Passed
