### ISSUE TITLE
Prevent multiple clicks of buttons that send web requests

### ISSUE THREAD

**Issue by AlexJYoungman** [innovationprogrammeuki/Absences#245]
Buttons such as the create on create absence and update on edit absence can be clicked multiple times, causing issues with the users allowance.

AC01: The buttons should be disabled after first click and then re enabled once the form is hidden

**Comment by danieljtate** [comment]
Testing 

1. Clicked on an absence
2. clicked edit
3. changed absence
4. multiple clicks on 'Update'
5. button disables and modal closes

Passed
