### ISSUE TITLE
All users option on Users page doesn't display

### ISSUE THREAD

**Issue by AlexJYoungman** [innovationprogrammeuki/Absences#247]

**Comment by AlexJYoungman** [comment]
Testing

1. Opened absences and logged in
2. Navigated to users page
3. Switched to all users
 
Failed. On Clicking a sort arrow, the list disappears.

**Comment by joerushbrooke** [comment]
Test - Number 2

    Opened absences and logged in
    Navigated to users page
    Switched to all users
    List does not change when 'All users' is selected - every other team shows.

Failed.

**Comment by joerushbrooke** [comment]
Test - Number 3

Opened absences and logged in
Navigated to users page
Switched to all users
List does change to all users.

Passed.
