### ISSUE TITLE
As a user, I want to log into the absence tool

### ISSUE THREAD

**Issue by KatherineGoldklang** [innovationprogrammeuki/Absences#25]
AC01: Can I log in to the tool?
AC02: If I enter the wrong credentials, can I see an error message?

**Comment by natalietolley** [comment]
![login flows 001](https://cloud.githubusercontent.com/assets/20187071/19191559/f21d7b60-8c9a-11e6-9430-0fc9ae4e4fde.jpeg)
![login flows 002](https://cloud.githubusercontent.com/assets/20187071/19191558/f21b10d2-8c9a-11e6-82c7-108c0713bb43.jpeg)
![login flows 003](https://cloud.githubusercontent.com/assets/20187071/19191557/f219e7f2-8c9a-11e6-9d1a-a088349bc299.jpeg)

**Comment by JohnThirlaway1** [comment]
I will pick this story up and hopefully get some work completed over the weekend.

**Comment by JohnThirlaway1** [comment]
made a start on this over the weekend, I have worked on the returning user 'Hello' screen however I need the background off UX Team and to work further on the change on click of the button to finish the user flow.

**Comment by JohnThirlaway1** [comment]
currently the screens for the first user flow have been put in place, I still need to put in place the requirement for the second flow.

**Comment by JohnThirlaway1** [comment]
functionality is now completed, I am awaiting to push this story for code review.

**Comment by JohnThirlaway1** [comment]
pushed into code review after clearing down merge conflicts, Alex has checked it and I have applied a few small indentation changes which he has requested and the story has been pushed back into code review
