### ISSUE TITLE
Refund holidays when a holiday is deleted functionality in the front end

### ISSUE THREAD

**Issue by AlexJYoungman** [innovationprogrammeuki/Absences#252]

**Comment by JohnThirlaway1** [comment]
Testing: 

- Logged into the application.
- Navigated to 'my calendar'.
-  Deleted holiday, once done this was then reflected in the allowance amount.

Status: Passed

**Comment by TheGarrett** [comment]
Testing (Fully tested):

Logged into the application.
Navigated to 'my calendar'.
Deleted pending holiday, once done this was then reflected in the allowance amount.
Deleted approved holiday, once done this was then reflected in the allowance amount.
Deleted other types, didn't remove from allowances.

Status: Passed
