### ISSUE TITLE
As a user, I want to be able to log out of the absence tool

### ISSUE THREAD

**Issue by KatherineGoldklang** [innovationprogrammeuki/Absences#26]
AC01: Can I log out of the tool?

**Comment by AlexJYoungman** [comment]
Added dropdown to top right where username is displayed, along with a log out button

**Comment by JohnThirlaway1** [comment]
I will be adding the functionality to pass the user back onto the login page.

**Comment by JohnThirlaway1** [comment]
have found a solution for this functionality, currently re-directing the user to the "My Calendar" screen at the moment due to the Login component not being within this branch.

**Comment by JohnThirlaway1** [comment]
currently having the logout send the user to the "My Calendar" for now as branches need to be merged in-order to pass the user the correct path for login component.
