### ISSUE TITLE
add a modal displaying a error message when a user tries to delete another persons absence

### ISSUE THREAD

**Issue by JohnThirlaway1** [innovationprogrammeuki/Absences#275]

**Comment by JohnThirlaway1** [comment]
Existing alert message was displaying, however replacing with better UI

**Comment by AlexJYoungman** [comment]
Testing

1. Logged into absences
2. Navigated to users page
3. Verified that a modal now displays instead of alert when deleting someone else's absence
4. Verified that I can still delete my own absence from team calendar

Passed.
