### ISSUE TITLE
As a team member I want to view the Company Calender so that I can see when my peers are absent

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#8]
AC01: Can I see the Company Calendar tab in the navigation?
AC02: Does the system allow me to navigate to the Company Calendar page?

**Comment by Michael-B-Lee** [comment]
The company calendar tab can be seen in the navigation bar and routing has been put in place that allows the system to navigate to the company calendar page. Currently working on styling of navbar.
