### ISSUE TITLE
Bug: Settings page - 'Absence Type' tick boxes not displaying ticks

### ISSUE THREAD

**Issue by KatherineGoldklang** [innovationprogrammeuki/Absences#88]
Tick box is working in 'Absence Type' pop up, however isn't displaying when listed in the 'Absence Type' box under 'Needs approval'

**Comment by Michael-B-Lee** [comment]
Have fixed the issue with "needs approval" check boxes not displaying, they now pull data from the db. However, this caused issues from the absence type pop up and so I've removed that tick box entirely. Any new absence types created will not require approval by default.
