### ISSUE TITLE
As a team leader I want to see the total number of absences today and total absence request so that I can action them

### ISSUE THREAD

**Issue by stevenhaynes** [innovationprogrammeuki/Absences#9]
AC01: Does the dashboard show the number of Absence requests?
AC02: Does the dashboard show the number of people Absent today?

**Comment by JohnThirlaway1** [comment]
Currently working on this story at the moment

**Comment by JohnThirlaway1** [comment]
Story is currently static due to database being connected as of yet, however the dashboard layout has been completed and the chart added with help of Daniel Tate & Alex. Due to being off tomorrow I have transfered him my code, please contact him until I am back into the office on  22/09/16.

**Comment by JohnThirlaway1** [comment]
Code has been cleaned up and reformatted and styled to match the UI. Waiting for the navbar code to be reviewed and approved before pushing my code to git for peer review. I will add another comment once the code has been pushed for code review.

**Comment by JohnThirlaway1** [comment]
Managed to style the pie chart to use Agfa Sans Serif font family, this has been done and I will pass my code over to Daniel due to being absent tomorrow and having to wait for Michael to make changes from his story.

**Comment by JohnThirlaway1** [comment]
![dash21-09](https://cloud.githubusercontent.com/assets/20187081/18718639/28a64d0a-801c-11e6-90c2-cc0881a0ec11.png)

**Comment by danieljtate** [comment]
Code has now been pushed for review

**Comment by JohnThirlaway1** [comment]
Cheers Dan, much appreciated!

**Comment by JohnThirlaway1** [comment]
Adam Kelly and Ryan Garrett have left some peer review comments. I will be working through these today and will advise which have been completed.

**Comment by JohnThirlaway1** [comment]
Applied changes required from Adam Kelly's code review which where the following:
In app/components/Dashboard.js:
> @@ -1,13 +1,332 @@
 var React = require('react');
+var ReactDOM = require('react-dom');
+var ReactBootstrap = require('react-bootstrap');
Bootstrap is already imported into the code base, there's no need to have it twice
-------John's Reaction-----------------
Deleted var ReactBootstrap = require(‘react-bootstrap’); - JT
________________________________________
In app/components/Dashboard.js:
> @@ -1,13 +1,332 @@
 var React = require('react');
+var ReactDOM = require('react-dom');
+var ReactBootstrap = require('react-bootstrap');
+var GChart = require('react-google-charts');
I don't see the value in using Google charts when d3 is being used in this project, you will be able to charting in d3.
--------John's Comment--------------------------------
Daniel Tate spoke to adam regarding this and advised that Adam Kelly preffered to use D3, however if it would be too much work it would be okay keeping the Google Charts integration.
________________________________________
In app/components/Dashboard.js:
>  
-var Dashboard = React.createClass({
+{/*Todays Absences*/}
+var NewComponent = React.createClass({
Bad naming convention
--------John's Comment-------------------
Changed NewComponent to TodaysAbsences
________________________________________
In app/index.html:
>    </head>
   <body>
     <div id="app"></div>
     <script src="../node_modules/jquery/dist/jquery.min.js"></script>
     <script src="../node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
+    <div id="data_pie"></div>
-------------John's Comment------------------
This is already being rendered in the component – Removed data_pie - JT
________________________________________
In app/styles/css/dashboardcss.css:
> @@ -0,0 +1,203 @@
+body{
Name of this file needs adjusting 
________________________________________
In app/styles/css/dashboardcss.css:
> @@ -0,0 +1,203 @@
+body{
+  margin:none;
+  font-family: Agfa Rotis Sans Serif;
+  src: url(ROTSAN.TTF);
+}
+
+#DashboardContainer {
+  width:1245px;
+  margin: auto;
+}
+h4 {
Your overwriting alot of global styles in this file which will cause big issues
----John's Comment-------------------------
Updated CSS and JS file to remove using a global style
________________________________________
In app/styles/css/dashboardcss.css:
> +}
+.absenceRequest {
+  display: flex;
+  position: relative;
+  width: 100%;
+  font-size: 16px;
+}
+.personContainer {
+  display:flex;
+  flex-direction:column;
+  padding-left: 20px;
+	width: 42%;
+  font-family:Agfa Rotis Sans Serif;
+  font-size: 18px;
+}
+.col-md-4 {
Do not overwrite bootstrap styles this will break other people's code and cause issues going forward
 –-John's Reply-----------------------------
 Done, renamed the col-md-4 CSS rule and Dashboard.js to be dashboardCol4Container
________________________________________
In app/components/Dashboard.js:
>  
-var Dashboard = React.createClass({
+{/*Todays Absences*/}
+var NewComponent = React.createClass({
+  render: function() {
+    return (
+    <div className="Absences">
+      <div className="col-md-8">
All of your HTML is hard-coded, you should make it dynamic and read the data from a JSON to mock the database 
---John's Reply---------------------------------
Hard-coded data has been swapped to JSON
________________________________________
In app/index.html:
>      <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta http-equiv="X-UA-Compatible" content="IE=edge" />
+    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
Im not sure what this is but if you rely on external files they might change or be removed which will break the app going forward.  
-John's Reply------------------------------------
Daniel Tate spoke to adam regarding this and advised that Adam Kelly preffered to use D3, however if it would be too much work it would be okay keeping the Google Charts integration.- JT

**Comment by JohnThirlaway1** [comment]
applied NG repeat to  tables, unfoutantly this has knocked some of the CSS out of lne which need to be fixed before pushing to git for code review and test.

**Comment by JohnThirlaway1** [comment]
Clean up css after using reacts version of NG Repeat and pushed to git for code review.  Dan has yet to complete the piechart within D3 and Ryan has been notified that the story has been pushed into code review

**Comment by JohnThirlaway1** [comment]
Made further changes this morning to the CSS and pushed for code review, Adam has taken a look at an earlier submission and point out a few issues which I have actioned and repushed up.

**Comment by JohnThirlaway1** [comment]
had to make a small change on the navigation,js & css in-order to remove an id in exchange for a CSS Rule.

**Comment by JohnThirlaway1** [comment]
Ryan has reviewed my code, left a changes which will need to be actioned in the form of indentation and coding practices.

**Comment by JohnThirlaway1** [comment]
Story is back into code review after ryan advised making changes to the JSON formatting and correct formating and spacing on functions.

**Comment by JohnThirlaway1** [comment]
Code is currently being reviewed by Ryan Garret and he has advised the story has passed , I will move the story into code review.

**Comment by JohnThirlaway1** [comment]
Adam Kelly has pointed out an issue with a  naming convention, I have changed this and pushed back upto git

**Comment by JohnThirlaway1** [comment]
Awaiting code review and requires a merge conflicts to be resolved, I will do this first thing in the morning as I will require assistance.

**Comment by JohnThirlaway1** [comment]
made changes making the dashboard fully responsive, I have completed this however I am having issues commit to github as I am recieving errors. I will be gettting further assistance this morning.

**Comment by JohnThirlaway1** [comment]
story has passed code review, adding small changes to the UI after sitting with natalie and doing a UI Review before merging to Master branch

**Comment by JohnThirlaway1** [comment]
story completed and pushed to master after successfully passing code review and  UI review after a few minor tweeks .
